// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DatabaseExampleGenerators
{
    using System.Data;
    using System.Linq;
    using System.Collections.Generic;
    using FluentMigrator;
    using JetBrains.ReSharper.Psi;
    using JetBrains.ReSharper.Psi.Util;
    using JetBrains.Util.Extension;
    using JetBrains.ProjectModel;
    using JetBrains.ReSharper.Psi.CSharp.Tree;
    using T4CodeGenerator.Generators.Core.Generators.Common;
    using T4CodeGenerator.Generators.Core.Helpers;
    using DatabaseExampleCore;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class MigrationGenerator : ByClassFileGeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            this.Write("\r\n");
            this.Write("\r\n");
            this.Write("\r\n\r\n");
            
            #line 19 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"

    void ProcessClass(IClassLikeDeclaration @class)
    {
        string tableName = Helpers.GetTableName(@class);
        Error(string.IsNullOrEmpty(tableName), $"Type '{@class.DeclaredName}' is not valid table type.");

		
            
            #line default
            #line hidden
            this.Write("\t\t\tthis.Create.Table(\"");
            
            #line 26 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.GetTableName(@class)));
            
            #line default
            #line hidden
            this.Write("\")\r\n\t\t\t\r\n\t\t\t");
            
            #line 28 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
foreach (IPropertyDeclaration property in @class.PropertyDeclarations.Where(x => !x.Type.IsCollectionLike())){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 29 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
LineBreak();
            
            #line default
            #line hidden
            this.Write("\t\t\t\t.WithColumn(\"");
            
            #line 30 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.DeclaredName));
            
            #line default
            #line hidden
            this.Write("\")\r\n\t\t\t\t");
            
            #line 31 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
WriteColumnType(property);
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 32 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
WriteNullability(property.Type);
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 33 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
WritePrimaryKey(property);
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 34 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
WriteForeignKey(property);
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 35 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
}
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t;\r\n\t\t");
            
            #line 38 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"

		
        foreach (IPropertyDeclaration property in @class.PropertyDeclarations)
        {
            if (property.Type.IsCollectionLike())
            {
                LineBreak();
                LineBreak();

                IType collectionElementType = 
					property.Type.GetGenericUnderlyingType(property.Type.GetTypeElement());
				IClassLikeDeclaration collectionElementTypeDeclaration = 
					collectionElementType.GetSingleDeclaration<IClassLikeDeclaration>();

                Error(collectionElementTypeDeclaration == null, $"Type '{collectionElementType.GetCSharpTypeName()}' is not valid table type.");

                ProcessClass(collectionElementTypeDeclaration);
            }
        }
    }

	void WriteColumnType(IPropertyDeclaration property)
    {
		IType type = property.Type;
        if (type.IsNullable())
        {
            type = type.GetNullableUnderlyingType();
        }

		
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 68 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
if (type.IsInt()) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t.AsInt32()\r\n\t\t\t");
            
            #line 70 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
} else if (type.IsString()) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t.AsString()\r\n\t\t\t");
            
            #line 72 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
} else if (type.IsDateTime()) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t.AsDate()\r\n\t\t\t");
            
            #line 74 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
} else if (type.IsTimeSpan()) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t.AsTime()\r\n\t\t\t");
            
            #line 76 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
} else {
			    Error($"The type '{type.GetCSharpTypeName()}' of property '{property.DeclaredName}' is unknown.");
			}
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 79 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"

    }

	void WriteNullability(IType propertyType)
    {
		
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 85 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
if (propertyType.IsReferenceType() || propertyType.IsNullable()) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t.Nullable()\r\n\t\t\t");
            
            #line 87 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
} else {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t.NotNullable()\r\n\t\t\t");
            
            #line 89 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 90 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"

    }

	void WritePrimaryKey(IPropertyDeclaration property)
    {
		if (property.HasAttribute<PrimaryKeyAttribute>())
		{
		    
            
            #line default
            #line hidden
            this.Write(".PrimaryKey()");
            
            #line 97 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"

		}
    }

	void WriteForeignKey(IPropertyDeclaration property)
    {
		if (Helpers.TryGetReferenceTableName(property, out string tableName))
		{
			
            
            #line default
            #line hidden
            this.Write("\t\t\t\t.ForeignKey(\"");
            
            #line 106 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableName));
            
            #line default
            #line hidden
            this.Write("\", \"Id\")\r\n\t\t\t\t");
            
            #line 107 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
if (tableName == this.TableName) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t.OnDelete(");
            
            #line 108 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeof(Rule)));
            
            #line default
            #line hidden
            this.Write(".Cascade)\r\n\t\t\t\t");
            
            #line 109 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
}
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 110 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"

		}
    }

            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 115 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.ExpectedNamespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\t[Migration(");
            
            #line 117 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.MigrationNumber));
            
            #line default
            #line hidden
            this.Write(")]\r\n\tpublic class M");
            
            #line 118 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.MigrationNumber));
            
            #line default
            #line hidden
            this.Write("_");
            
            #line 118 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.TableName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 118 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeof(Migration)));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tpublic override void Up() \r\n\t\t{ \r\n\t\t\t");
            
            #line 122 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
ProcessClass(this.Class);
            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t\tpublic override void Down() \r\n\t\t{ \r\n\t\t\tthrow new ");
            
            #line 127 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeof(NotImplementedException)));
            
            #line default
            #line hidden
            this.Write("();\r\n\t\t}\r\n\t}\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 132 "C:\T4CodeGeneratorExamples\DatabaseExampleGenerators\MigrationGenerator.tt"

    public string TableName { get; set; }

    public int MigrationNumber { get; set; }

    public override string Name => "Full migration";
	
    public override string GetFileName() =>
        $"DatabaseExampleProject\\Migrations\\M{this.MigrationNumber}_{this.TableName}.cs";

    public override bool IsAvailableCore()
    {
        this.TableName = Helpers.GetTableName(this.Class);

        if (this.TableName == null)
        {
            return false;
        }

        IProjectFolder migrationsFolder = 
            this.DataProvider.Project.GetSubFolders().FirstOrDefault(x => x.Name == "Migrations");

        if (migrationsFolder == null)
        {
            return false;
        }

        IList<IProjectFile> migrationFiles = migrationsFolder.GetSubFiles();

        foreach (IProjectFile migrationFile in migrationFiles)
        {
            if (int.TryParse(migrationFile.Name.SubstringAfter("M").SubstringBefore("_"), out int migrationNumber))
            {
                this.MigrationNumber = Math.Max(this.MigrationNumber, migrationNumber + 1);
            }
        }

        return true;
    }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
