// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 15.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ExampleGenerators
{
    using JetBrains.ReSharper.Psi;
    using JetBrains.ReSharper.Psi.CSharp.Tree;
    using JetBrains.ReSharper.Psi.Tree;
    using T4CodeGenerator.Generators.Core.StructuralSearch.Attributes;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\T4CodeGeneratorExamples\ExampleGenerators\ReplaceLinqFirstAssignmentExpression.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class ReplaceLinqFirstAssignmentExpression : ReplaceLinqFirstExpressionBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            this.Write("\r\n");
            this.Write("\r\n");
            
            #line 9 "C:\T4CodeGeneratorExamples\ExampleGenerators\ReplaceLinqFirstAssignmentExpression.tt"
Render();
            
            #line default
            #line hidden
            this.Write("\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 11 "C:\T4CodeGeneratorExamples\ExampleGenerators\ReplaceLinqFirstAssignmentExpression.tt"

	[ExpressionPlaceholder]
	public IReferenceExpression TargetExpression { get; set; }

    public override bool Visible => true;

	protected override string Pattern => "$TargetExpression$ = $Enumerable$.First($Argument$ => $Condition$);";

    protected override ITreeNode Target => this.TargetExpression;

    protected override IType TargetType => this.TargetExpression.Type();


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
